# Generated by Django 3.1.12 on 2022-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200317_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kerkesat',
            new_name='solicitudt',
        ),
    ]
